[config]

;===================================================================
;下面是系统设置
;分辨率
screen_width=1920
screen_height=1080

;窗口偏移
window_Left=0
window_Top=0

;是否显示鼠标
showcursor=false

;是否全屏   全屏= 0,   窗口=1 ，窗口无边框= 2,
fullscreen=2

;置顶模式   置底= -1,  普通= 0,  开启时置顶= 1， 永久置顶=2 
screenDepth=2

;是否播放背景音乐
isAllowPlayBGM=true

;同时播放音效上限
audioShotLimit=5

;DebugLog输出过滤   全部=0, Warning以上=1，Assert以上=2,Error以上=3,不输出=4
logType=0

;Log日志保存
saveLog=true

;是否广播Debug
broadcastDebug=true

;是否打印socket消息   不打印=0, 打印简单消息=1, 打印完整消息=2
debugSocketMsgMode=1

;帧数限制
targetFramerate=60

;按键触发等级  全部触发=0  触发1以上=1  。。。
keyDownActionLevel=0

;资源回收时间(int) 小于等于0为不回收
releaseTime=30